Louise dev
ShuyunLiuRun/HomeApp--Items-classification-App pull request #5
Opened 2020-11-24 06:29 UTC by ShuyunLiuRun

As a user, I want to have an apparent button so that I can click on it and delete an item in the recorder. 

So I add a delete icon in every card which represents an item in the recorder. When the user clicks on it, there will be a dialogue saying that are you sure you want to delete this item. If the user chooses yes, the item will be deleted from the database and the website. The page will refresh after the dialogue close.

2020-11-24 07:22 UTC, KamikidFu requested changes

2020-11-24 07:22 UTC, kamifoo commented on app/src/App.js
> +  if (init === true) {
```suggestion
  if (init) {
```

2020-11-24 07:22 UTC, kamifoo commented on app/src/App.js
>      console.log(name + ID);
```suggestion
   
```

2020-11-24 07:22 UTC, kamifoo commented on app/src/App.js
>        if (response) {
Do we need any specific checking here?

2020-11-24 07:22 UTC, kamifoo commented on app/src/App.js
> +    console.log("new item: " + JSON.stringify(dataFromForm));
```suggestion
    
```

2020-11-24 07:22 UTC, kamifoo commented on app/src/App.js
> +const baseUrl = "http://localhost:4000/";
```suggestion
const BaseUrl = "http://localhost:4000/";
const ApiCommander = {
   AddItem: ()=>{return BaseUrl + 'addItem/';},
   GetContainerInfo: (containerId) => {return BaseUrl + 'containerInfo/' + containerId},
   //...
}
```

2020-11-24 07:22 UTC, kamifoo commented on app/src/App.js
> +    Fetch.get(baseUrl).then((res) => {
Just wondering what can we get from base url?

2020-11-24 07:22 UTC, kamifoo commented on app/src/App.js
> +    Fetch.post(baseUrl + "addItem/", dataFromForm).then((response) => {
```suggestion
    Fetch.post(ApiCommander.AddItem(), dataFromForm).then((response) => {
```

2020-11-24 07:22 UTC, kamifoo commented on app/src/App.js
> +      Fetch.get(baseUrl + "containerInfo/" + currentContainerId).then((response) => {
```suggestion
      Fetch.get(ApiCommander.GetContainerInfo(currentContainerId)).then((response) => {
```

2020-11-24 07:22 UTC, kamifoo commented on app/src/components/DataComponent.js
> +export const de = (url)=>{
Can we please name it as remove()?

2020-11-24 07:22 UTC, kamifoo commented on app/src/App.js
> +const baseUrl = "http://localhost:4000/";
Oh actually, any reason why we not put this url info in DataComponent.js? As I can see that file is where handling http requests.

2020-11-24 07:22 UTC, KamikidFu commented on app/src/components/Item/AddItemForm.js
> +  const handleAIChange = (event) => {
We should avoid to use abbreviation to name a method to achieve better readbility.

2020-11-24 07:22 UTC, KamikidFu commented on app/src/components/Item/ClickOnOneItem.js
> +    console.log("containerLabel"+containerLabel);
```suggestion

```

2020-11-24 07:22 UTC, KamikidFu commented on app/src/components/Item/OneItem.js
> +  const handleCloseTrue = () => {
```suggestion
  const handleDialogWhenYes = () => {
```

2020-11-24 07:22 UTC, KamikidFu commented on app/src/components/Item/OneItem.js
> +  const handleCloseFalse = () => {
And here

2020-11-24 07:22 UTC, KamikidFu commented on server/server.js
> +app.get('/', async (req, res, next) => {
Please consider to merge this with `/container/:id` get request handler method and leave it returning nothing.

2020-11-24 07:22 UTC, KamikidFu commented on server/server.js
> +app.get('/:id', function (req, res, next) {
Can you please change the `/:id` to `/container/:id`? As it is querying container

2020-11-24 07:22 UTC, KamikidFu commented on server/server.js
> +app.get('/containerInfo/:id', function (req, res, next) {
Please consider to change it as `/item/:id` as here querying item id

2020-11-24 07:22 UTC, KamikidFu commented on server/server.js
> +    var adInfo = req.body.additional_information;
Please change these variable name, `adInfo`, `isC`, `cB`

2020-11-24 07:22 UTC, KamikidFu commented on server/server.js
> +app.delete('/deleteItem/:id', function (req, res) {
Also, you can handle delete request by `/item/:id` url as well.
```suggestion
app.delete('/item/:id', function (req, res) {
```

2020-11-24 07:22 UTC, KamikidFu commented on server/server.js
> +app.post('/addItem', function (req, res) {
Please use `/item` url with post request
```suggestion
app.post('/item', function (req, res) {
```

2020-11-24 07:23 UTC, KamikidFu commented
Empty GoBack.js has been deleted, please refer to commit tab

2020-11-24 08:55 UTC, KamikidFu approved these changes
Cheers

2020-11-26 01:46 UTC, merged

2020-11-26 01:47 UTC, ShuyunLiuRun commented
Delete Item works.